config/routes.rb
Rails.application.routes.draw do
root to: "cocktails#index"
  resources :cocktails, only: [:new, :create, :index, :show, :edit, :update]
  resources :cocktails do
    resources :doses, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :ingredient_id, scope: :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
    @cocktail.save
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<div class="card-product">

  <div class="card-product-infos">
    <h2> Edit <%= @cocktail.name %></h2>
  <%= simple_form_for (@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.association :doses %>
  <%= f.submit "click here to edit"%>
  <% end %>
  </div>
</div>

app/views/cocktails/index.html.erb
<br>
<br>
<br>


  <div class="cards test">
  <% @cocktails.each do |cocktail|  %>
  <% if cocktail.photo.attached? %>

  <div class="card-category div-size" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.photo.key, crop: :fill %>)">
    <h2 class="fonts"> <%= link_to cocktail.name, cocktail_path(cocktail) %> </h2>
  </div>
<% else %>

  <div class="card-category div-size" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500)">
    <h2 class="fonts"> <%= link_to cocktail.name, cocktail_path(cocktail) %> </h2>
  </div>

<% end %>
<% end %>
</div>

app/views/cocktails/new.html.erb
<div class="card-product">

  <div class="card-product-infos">
    <h2> Add a Cocktail</h2>
  <%= simple_form_for (@cocktail) do |f| %>
  <%= f.input :name %>
   <%= f.input :photo, as: :file  %>
  <%= f.submit "click here to add a new cocktail"%>
  <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
 <br>
 <br>
<% if @cocktail.photo.attached? %>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>)">
    <h2> <%=  @cocktail.name %></h2>
  </div>
<% else %>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500">
    <h2> <%=  @cocktail.name %></h2>
  </div>

<% end %>


<div class="container">
  <h3> Ingredients </h3>
  <% @cocktail.doses.each do |d| %>
  <%= d.description %>
  <%= d.ingredient.name %>
    <%= link_to "delete ingredient", cocktail_dose_path(@cocktail, d), method: :delete  %>
  <% end %>
</div>

  <%= link_to "edit", edit_cocktail_path(@cocktail)  %>
  <br>
  <%= link_to "add an ingredient", new_cocktail_dose_path(@cocktail)  %>
  <br>

app/views/doses/new.html.erb
<div class="card-product">

  <div class="card-product-infos">
    <h2> Add a dose </h2>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "click here to edit"%>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8003273767.js" crossorigin="anonymous"></script>
  </head>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/header" %>
    <%= yield %>
  </body>

</html>

app/views/shared/_header.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/605408/pexels-photo-605408.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500)">
  LIST OF COCKTAILS
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/cocktails">
    <i class="fas fa-cocktail" ></i>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="btn btn-flat" href="/cocktails/new">Add a Cocktail</a>

      </li>


    </ul>
  </div>
</div>